config/routes.rb
Rails.application.routes.draw do
  resources :white_lists
  post 'white_lists/editar_lista_blanca'

  resources :filtersnos
  post 'filtersnos/consultaFiltros'
  get 'alert_release/index'

  post 'users/expire', to: 'users#expire'
  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'

  filter :locale


  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'



  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'alertn/observaciones' #, to: 'alertn#observaciones'
  post 'alertn/creacion_observaciones'
  post 'alertn/agregar_a_lista_blanca'
  post 'alertn/bloqueo_de_cuenta'



  #, to: 'alertn#observaciones'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :home, only: [:index, :create]
  resources :trcestatus


   # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/alertn.rb
class Alertn < ApplicationRecord
end

app/controllers/alertn_controller.rb
class AlertnController < ApplicationController
  # before_action :set_alertn, only: [:show, :edit, :update, :destroy]

  # GET /alertn
  # GET /alertn.json
  @@byNewTran = "New Alert Transaccional"
  @@byNewPer = "New Alert Perfiles"


  #Asi estan en Liver
  # @@byNewTran = "New Alert Transaccional"
  # @@byNewPer = "New Alert Perfiles"

  def index
    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

        @per_n_tran.each do |permisos|
          @leerNewTran = permisos.leer

          if permisos.view_name == @@byNewTran

            @@crearNewTran = permisos.crear
            @@editarNewTran = permisos.editar
            @@leerNewTran = permisos.leer
            @@eliminarNewTran = permisos.eliminar

            @crearNewTran = permisos.crear
            @editarNewTran = permisos.editar
            @leerNewTran = permisos.leer
            @eliminarNewTran = permisos.eliminar
          end
        end

        @per_n_per = Permission.where("view_name = 'New Alert Perfiles' and profile_id = ?", @cu)

        @per_n_per.each do |permisos|
          @leerNewPer = permisos.leer

          if permisos.view_name == @@byNewPer

            @@crearNewPer = permisos.crear
            @@editarNewPer = permisos.editar
            @@leerNewPer = permisos.leer
            @@eliminarNewPer = permisos.eliminar

            @crearNewPer = permisos.crear
            @editarNewPer = permisos.editar
            @leerNewPer = permisos.leer
            @eliminarNewPer = permisos.eliminar
          end

        end

        if current_user.habilitado == 0

          if (@@leerNewPer == 2 || @@leerNewTran == 2)

            @bitaAlertasxAtender = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
            @bitaAlertasxAtender = Tbitacora.where(:IdUsuario => 'N/A')

            @alert_Tran = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
            @alert_Per = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count
          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_enabled')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end

  # GET /alertn/1
  # GET /alertn/1.json
  def show
    if current_user.habilitado == 0
    else
      @Without_Permission = 100
      redirect_to home_index_path, :alert => t('all.not_enabled')
    end
  end

  # GET /alertn/new
  def new
    if current_user.habilitado == 0
      @alertn = Alertn.new
    else
      @Without_Permission = 100
      redirect_to home_index_path, :alert => t('all.not_enabled')
    end
  end

  # GET /alertn/1/edit
  def edit
    if current_user.habilitado == 0
    else
      @Without_Permission = 100
      redirect_to home_index_path, :alert => t('all.not_enabled')
    end

  end

  # POST /alertn
  # POST /alertn.json
  def create
    @alertn = Alertn.new(alertn_params)

    respond_to do |format|
      if @alertn.save
        format.html {redirect_to @alertn, notice: 'Alertn was successfully created.'}
        format.json {render :show, status: :created, location: @alertn}
      else
        format.html {render :new}
        format.json {render json: @alertn.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /alertn/1
  # PATCH/PUT /alertn/1.json
  def update
    respond_to do |format|
      if @alertn.update(alertn_params)
        format.html {redirect_to @alertn, notice: 'Alertn was successfully updated.'}
        format.json {render :show, status: :ok, location: @alertn}
      else
        format.html {render :edit}
        format.json {render json: @alertn.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /alertn/1
  # DELETE /alertn/1.json
  def destroy

    if current_user.habilitado == 0
      @alertn.destroy
      respond_to do |format|
        format.html {redirect_to alertns_url, notice: 'Alertn was successfully destroyed.'}
        format.json {head :no_content}
      end
    else
      @Without_Permission = 100
      redirect_to home_index_path, :alert => t('all.not_enabled')
    end
  end

  def alertTran

    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

        @per_n_tran.each do |permisos|
          @crearNewTran = permisos.crear
          @editarNewTran = permisos.editar
          @leerNewTran = permisos.leer

          if permisos.view_name == @@byNewTran

            @@crearNewTran = permisos.crear
            @@editarNewTran = permisos.editar
            @@leerNewTran = permisos.leer
            @@eliminarNewTran = permisos.eliminar

            @crearNewTran = permisos.crear
            @editarNewTran = permisos.editar
            @leerNewTran = permisos.leer
            @eliminarNewTran = permisos.eliminar
          end
        end

        if current_user.habilitado == 0

          if (@@leerNewTran == 2)

            st = Testadosxalerta.select(:IdEstado, :falso_positivo).all
            gon.estados = st
            gon.false = true

            ## Todos los filtros
            @hash_filtros = {}
            filtros = TxFilters.all
            filtros.each do |fil|
              @hash_filtros.store(fil.Id, "#{fil.Id}-#{fil.Description}")
            end

            #Todos los estados
            @hash_states = {}
            states = Testadosxalerta.all
            states.each do |sta|
              @hash_states.store(sta.IdEstado, "#{sta.IdEstado}-#{sta.Descripcion}")
            end

            #Todos los usuarios
            @hash_users = {}
            users = User.all
            users.each do |usr|
              @hash_users.store(usr.id, "#{usr.name} #{usr.last_name}")
            end


            ### Segimiento de alerta
            @idObseTran = params[:id]

            if params[:id]

              @id_consulta = params[:id]
              @alerta_Tran = Tbitacora.where(:Id => @id_consulta).first
              @obser = Tbitaobse.where(:IdAlerta => params[:id]).order("Id Desc")
              @nuevo = true

              regresar = Tatendiendo.where("IdTran = #{@alerta_Tran.IdTran}")


              # @observaciones = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc").page(params[:page]).per(10) #Historial de observaciones Vista
              # @observaciones = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc") #Historial de observaciones Vista
              # @@Observaciones = @observaciones
              @observaciones_xls = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc") #Historial de observaciones Excel



              #Esto Agregar los datos del usuario y alerta IdTran =
              @atendiendo = Tatendiendo.new
              @atendiendo.IdUsuario = current_user.id
              @atendiendo.IdTran = @alerta_Tran.IdTran
              @atendiendo.save

              ### Cuando guarda la observacion de una nueva alerta / Está no es la modal
            elsif params[:observaciones]
              @id_tran = params[:id]
              @id_consulta = @id_tran
              @alerta_Tran = Tbitacora.where(:Id => @id_tran).first
              @obser = Tbitaobse.where(:IdAlerta => params[:id]).order("Id Desc")
              @nuevo = true

              # @observaciones = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc").page(params[:page]).per(10)
              # @observaciones = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc").page(params[:page]).per(10)
              # @@Observaciones = @observaciones
              @observaciones_xls = Tbitaobse.where(:IdAlerta => @id_consulta).order("Id Desc")

              ### Cuando entra a atender una nueva alerta
            else
              #Verificar si el usuario ya tenía cuentas atendiendo actualmente
              @cuentas_ocupando = Tatendiendo.where(:IdUsuario => current_user.id)

              # Si tiene cuentas atendiendo se elimina de Tatendiendo la cuenta.
              if @cuentas_ocupando.present? && !@cuentas_ocupando.nil?
                @cuentas_ocupando.each do |cta|
                  cta.destroy
                end
              end

              #Verificar si hay cuentas que se están atendiendo de otros usuarios
              @cuentas_ocupadas = Tatendiendo.all
              query = ""

              ### Se hace un query donde no se incluyan las cuentas que se estan atendiendo por otros usuarios
              if @cuentas_ocupadas.present? && !@cuentas_ocupadas.nil?
                @cuentas_ocupadas.each do |cta|
                  if query == ""
                    # query = query + "#{t('config.main')} != '#{cta.IdTran}'"
                    query = query + "IdTran != '#{cta.IdTran}'"
                  else
                    # query = query + " and #{t('config.main')} != '#{cta.IdTran}'"
                    query = query + " and IdTran != '#{cta.IdTran}'"
                  end
                end
              end

              # Verificar las prioridades del usuario
              @prioridades_usuario = Txfilterxusr.where(:IdUsuario => current_user.id)
              if @prioridades_usuario.present? && !@prioridades_usuario.nil?
                @prioridades_usuario.each do |prio|
                  if query == ""
                    query = query + "IdFiltro = #{prio.Txfiltro_id}"
                  else

app/helpers/alertn_helper.rb
module AlertnHelper
end

app/views/alertn/_form.html.erb
<%= form_for(alertn) do |f| %>
  <% if alertn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alertn.errors.count, "error") %> prohibited this alertn from being saved:</h2>

      <ul>
      <% alertn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alertn/_historialAlertas.html.erb
<% begin %>

<% puts "Controlador consulta en la vista #{@ConsultaHistTbit.count} Present?: #{@ConsultaHistTbit.present?}" %>
  <% if @ConsultaHistTbit.present? %>
    <div class="row">
      <div class="col-sm-7"></div>
      <div class="col-sm-5 text-right">
        <div style="margin-bottom: 2em;">
          <div class="detall_left" id="cont">
            <%= page_entries_info @ConsultaHistTbit, entry_name: t('activerecord.all.alert') %>
          </div>
          <div class="pag_right" id="paginator">
            <%= paginate @ConsultaHistTbit, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true, params: {:id => @IdAlerta, :kam => 'hist', :observaciones => nil} %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-10"></div>
      <div class="col-sm-2 text-right ">
        <button type="button" class="btn btn-xs btn-primary unsel" id="check_all">
          <i class="fa fa-plus-square" aria-hidden="true"></i>
          <label> <%= t('views.permisos_edit.select') %> </label>
        </button>
      </div>
    </div>

    <br>
    <table class="table table-bordered table- table-condensed table-striped" id="tab">
      <thead>
      <tr>
        <th width="15"></th>
        <th><%= t('views.new_alert_tran.ticket') %></th>
        <th><%= t('views.new_alert_tran.date_hour') %></th>
        <th><%= t('views.new_alert_tran.origin_s') %></th>
        <th><%= t('views.new_alert_tran.filter') %></th>
        <th><%= t('views.new_alert_tran.state') %></th>
        <th><%= t('views.new_alert_tran.analyst') %></th>
        <% if @editarNewTran == 4 %>
          <th><%= t('views.new_alert_tran.attend') %></th>
        <% end %>
      </tr>
      </thead>

      <tbody id="alertas_hist">
        <%= render @ConsultaHistTbit %>
      </tbody>
    </table>
    <div class="row">
      <div class="col-sm-7"></div>
      <div class="col-sm-5 text-right">
        <div style="margin-bottom: 2em;">
          <div class="pag_right" id="paginator_p">
            <%= paginate @ConsultaHistTbit, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true, params: {:id => @IdAlerta, :kam => 'hist', :observaciones => nil} %>
          </div>
          <div class="detall_left" id="cont_p">
            <%= page_entries_info @ConsultaHistTbit, entry_name: t('activerecord.all.alert') %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <label><%= t('views.new_alert_tran.no_alerts') %></label>
  <% end %>



<%# if @ConsultaHistTbit.present? %>
  <%#  puts" Estoy en la vista #{@ConsultaHistTbit.count}"%>


<!--  <div class="row">-->
<!--    <div class="col-sm-10"></div>-->
<!--    <div class="col-sm-2 text-right ">-->
<!--      <button type="button" class="btn btn-xs btn-primary unsel" id="check_all">-->
<!--        <i class="fa fa-plus-square" aria-hidden="true"></i>-->
<!--        <label> <%#= t('views.permisos_edit.select') %> </label>-->
<!--      </button>-->
<!--    </div>-->
<!--  </div>-->

<!--  <br>-->
<!--  <table class="table table-bordered table- table-condensed table-striped" id="tab">-->
<!--    <thead>-->
<!--    <tr>-->
<!--      <th width="15"></th>-->
<!--      <th><%#= t('views.new_alert_tran.ticket') %></th>-->
<!--      <th><%#= t('views.new_alert_tran.date_hour') %></th>-->
<!--      <th><%#= t('views.new_alert_tran.origin_s') %></th>-->
<!--      <th><%#= t('views.new_alert_tran.filter') %></th>-->
<!--      <th><%#= t('views.new_alert_tran.state') %></th>-->
<!--      <th><%#= t('views.new_alert_tran.analyst') %></th>-->
      <%# if @editarNewTran == 4 %>
<!--        <th><%#= t('views.new_alert_tran.attend') %></th>-->
      <%# end %>
<!--    </tr>-->
<!--    </thead>-->

<!--    <tbody id="alertas_hist">-->
    <%#= render @ConsultaHistTbit %>

<!--    </tbody>-->
<!--  </table>-->

<%# else %>
<!--  <label><%#= t('views.new_alert_tran.no_alerts') %></label>-->
<%# end %>

<script type="text/javascript" charset="utf-8">
    <% if @nuevo %>
      localStorage.setItem("Selected", "");
    <% end %>

    $(function(){
        var elem = document.querySelector('.js-switch');
        var switchery = new Switchery(elem, {color: '#1AB394'});

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });

        $(".ref").click(function () {
            var id = $(this).children(".id_tran").children(".linkTran").html()
            var tiene = $("#head" + id).hasClass("cerrado")

            if (tiene) {
                $("#head" + id).show()
//            $("#content_ref" + id).show()
                $("#head" + id).removeClass("cerrado")
//            $("#content_ref" + id).removeClass("cerrado")
                $("#head" + id).addClass("abierto")
                $(this).children(".show").html("")
                $(this).children(".show").append('<i class="fa fa-minus-square" aria-hidden="true"></i>')
//            $("#content_ref" + id).addClass("abierto")
            } else {
                $("#head" + id).hide()
//            $("#content_ref" + id).hide()
                $("#head" + id).removeClass("abierto")
//            $("#content_ref" + id).removeClass("abierto")
                $("#head" + id).addClass("cerrado")
                $(this).children(".show").html("")
                $(this).children(".show").append('<i class="fa fa-plus-square" aria-hidden="true"></i>')
//            $("#content_ref" + id).addClass("cerrado")
            }

        })

        $("#state_ob").change(function () {
            var valor = $(this).val()

            for (i = 0; i < gon.estados.length; i++) {
                if (gon.estados[i].IdEstado == valor) {
                    var def = gon.estados[i].falso_positivo
                    console.log('valor de def: ' + def)

                    if (def == 0) {
                        $("#fraud_no").iCheck('check')
                        $("#fraud_yes").iCheck('uncheck')
                        $("#fraud_no").iCheck('disable')
                        $("#fraud_yes").iCheck('disable')
                    } else if (def == 1) {
                        $("#fraud_no").iCheck('uncheck')
                        $("#fraud_yes").iCheck('check')
                        $("#fraud_no").iCheck('disable')
                        $("#fraud_yes").iCheck('disable')
                    } else if (def == 2) {
                        $("#fraud_no").iCheck('uncheck')
                        $("#fraud_yes").iCheck('uncheck')
                        $("#fraud_no").iCheck('enable')
                        $("#fraud_yes").iCheck('enable')
                    }
                    break;
                }
            }
        })

        $('#tab input:checkbox').on('ifChecked', function (event) {
            //SOY DE ALERTTRAN
            console.log("me seleccionaron")
            var lc = localStorage.getItem("Selected");
            var selected = $(this).val();
            var checked_alert = lc.split(',')

            var existe = jQuery.inArray(selected, checked_alert)

            if (existe == -1) {
                if (lc == "") {
                    localStorage.setItem("Selected", lc + selected);
                } else {
                    localStorage.setItem("Selected", lc + "," + selected);
                }
            }

            $("#valor").val(localStorage.getItem("Selected"))

            var lc = $("#valor").val()
            // console.log(lc.length)
            // console.log(lc)
            if (lc.length == 0){
                $('#apply_obse').iCheck('disable');
                $('#apply_obse').iCheck('uncheck');
            }else {
                $('#apply_obse').iCheck('enable');
            }
        });

        $('#tab input').on('ifUnchecked', function (event) {
            // SOY DE ALERTTRAN
            console.log("no me seleccionaron")
            var lc = localStorage.getItem("Selected");
            var selected = $(this).val();
            var checked_alert = lc.split(',')

            var existe = jQuery.inArray(selected, checked_alert)

            if (existe != -1) {
                checked_alert.splice(existe, 1)
                checked_alert = checked_alert.join(",");
                localStorage.setItem("Selected", checked_alert)
            }

            $("#valor").val(localStorage.getItem("Selected"))

            var seleccionados = $("#tab input:checkbox:checked").map(function () {
                return $(this).val()
            }).get();

            if (seleccionados.length < 10) {
                $("#check_all").removeClass("sel")
                $("#check_all").addClass("unsel")
                $("#check_all").html('');
                $("#check_all").append('<i class="fa fa-minus-square" aria-hidden="true"></i> <label> <%= t('views.permisos_edit.select') %> </label>')
            } else {
                $("#check_all").removeClass("unsel")
                $("#check_all").addClass("sel")
                $("#check_all").html('');
                $("#check_all").append('<i class="fa fa-minus-square" aria-hidden="true"></i> <label> <%= t('views.permisos_edit.unselect') %> </label>')
            }

            var lc = $("#valor").val()
            console.log(lc.length)
            console.log(lc)
            if (lc.length == 0){
                $('#apply_obse').iCheck('disable');
                $('#apply_obse').iCheck('uncheck');
            }else {
                $('#apply_obse').iCheck('enable');
            }
        });

        $("#check_all").css("width", "155")

        $("#check_all").click(function () {
            console.log("clic todos")
            var tiene = $(this).hasClass("unsel")

            if (tiene) {
                $(this).removeClass("unsel")
                $(this).addClass("sel")
                $(this).html('');
                $(this).append('<i class="fa fa-minus-square" aria-hidden="true"></i> <label> <%= t('views.permisos_edit.unselect') %> </label>')

                $("#tab input:checkbox").map(function () {
                    $(this).iCheck('check')

                    var lc = localStorage.getItem("Selected");
                    <% alertas = "" %>
                    <% cont = 0 %>
                    <% @ConsultaHistTbit_xls.each do |h| %>
                    <% if cont == 0  %>
                    <% cont += 1 %>
                    <% alertas = alertas + h.Id.to_s %>
                    <% else  %>
                    <% alertas = alertas + ',' + h.Id.to_s %>
                    <% end %>
                    <% end %>

                    var selected = "<%= alertas %>"
                    localStorage.setItem("Selected", selected);

                    $('#apply_obse').iCheck('enable');

                    $("#valor").val(localStorage.getItem("Selected"))
                }).get();

            } else {
                $(this).removeClass("sel")
                $(this).addClass("unsel")
                $(this).html('');
                $(this).append('<i class="fa fa-minus-square" aria-hidden="true"></i> <label> <%= t('views.permisos_edit.select') %> </label>')

                $("#tab input:checkbox").map(function () {
                    $(this).iCheck('uncheck')
                    localStorage.setItem("Selected", "")

                    $("#valor").val(localStorage.getItem("Selected"))

                    $('#apply_obse').iCheck('disable');
                }).get();
            }

            console.log($("#valor").val())
        })

        <% if @crearNewTran == 8 %>
        $(".xls_g").click(function () {
            var id = this.id;
            var idioma = $("#idioma").val()
            $.ajax({
                type: "GET",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                },
                url: "/alertn/alertTran?id=" + id + "&xls_g=true" + "&user_id=<%= current_user.id %>" + "&idioma=" + idioma,
                data: {"_method": "alertTran"},
            })

            toastr.options = {
                closeButton: true,
                progressBar: true,
                showMethod: 'slideDown',
                timeOut: 5000
            };
            toastr.success("<%= t('views.xls_a.message') %>", "<%= t('views.xls_a.message2') %>");
        })
        <% end %>
    })
</script>

<style>

  <%# if @camposref.length > 5 %>
  .ref-wrapper {
    width: 100%;
    white-space: nowrap;
    overflow-y: hidden;
    overflow-x: scroll;
    -webkit-overflow-scrolling: touch;
  }

  .reference-table {
    display: table;
    margin-right: 20px;
  }

  .ref-wrapper::-webkit-scrollbar-track {
    -webkit-box-shadow: #003057;
    background-color: #CCCCCC;
  }

  .ref-wrapper::-webkit-scrollbar {
    width: 5px;
    height: 8px;
    background-color: #F5F5F5;
  }

  .ref-wrapper::-webkit-scrollbar-thumb {
    background-color: #FFF;
    background-image: -webkit-linear-gradient(90deg,
    #3472a4 0%,
    #3472a4 25%,
    transparent 100%,
    #3472a4 75%,
    transparent)
  }

  <%# end %>

</style>
  <%
  rescue => e
  puts 'Archivo: log/error_histAlertas.log'
  logger = Logger.new("log/error_histAlertas.log")
  logger.error('----------------------------------------------------------')
  logger.error(e)
  %>

<% end %>

app/views/alertn/_observaciones.html.erb
<%= javascript_include_tag 'iCheck/icheck.min' %>

<%#= @hola %>
<%#= @obser.present? %>
<% if @obser.present? %>


<!--  <div class="row">-->
<!--    <div class="col-sm-7"></div>-->
<!--    <div class="col-sm-5 text-right">-->
<!--      <div style="margin-bottom: 2em;">-->
<!--        <div class="detall_left" id="cont_obse">-->
          <%#= page_entries_info @obser, entry_name: t('views.new_alert_tran.obse') %>
<!--        </div>-->
<!--        <div class="pag_right" id="paginator_obse">-->
          <%#= paginate @obser, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->

  <div class="content-hist-trans">
    <table class="table table-bordered table- table-condensed table-striped">
      <thead>
      <tr>
        <th><%= t('views.new_alert_tran.date_hour') %></th>
        <th><%= t('views.new_alert_tran.obse') %></th>
        <th><%= t('views.new_alert_tran.state') %></th>
        <th><%= t('views.new_alert_tran.user_atn') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @obser %> <!----------   --------->
      </tbody>
    </table>
  </div>

<!--  <div class="row">-->
<!--    <div class="col-sm-7"></div>-->
<!--    <div class="col-sm-5 text-right">-->
<!--      <div style="margin-bottom: 2em;">-->
<!--        <div class="pag_right" id="paginator_p_obse">-->
          <%#= paginate @obser, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
<!--        </div>-->
<!--        <div class="detall_left" id="cont_p_obse">-->
          <%#= page_entries_info @obser, entry_name: t('views.new_alert_tran.obse') %>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<% else %>
  <label><%= t('views.new_alert_tran.no_alerts_ob') %></label>
<% end %>

app/views/alertn/edit.html.erb
<h1>Editing Alertn</h1>

<%= render 'form', alertn: @alertn %>

<%= link_to 'Show', @alertn %> |
<%= link_to 'Back', alertns_path %>

app/views/alertn/new.html.erb
<h1>New Alertn</h1>

<%= render 'form', alertn: @alertn %>

<%= link_to 'Back', alertns_path %>

app/views/alertn/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_alertn_path(@alertn) %> |
<%= link_to 'Back', alertns_path %>