config/routes.rb
Rails.application.routes.draw do
  resources :white_lists
  post 'white_lists/editar_lista_blanca'

  resources :filtersnos
  post 'filtersnos/consultaFiltros'
  get 'alert_release/index'

  post 'users/expire', to: 'users#expire'
  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'

  filter :locale


  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'



  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'alertn/observaciones' #, to: 'alertn#observaciones'
  post 'alertn/creacion_observaciones'
  post 'alertn/agregar_a_lista_blanca'
  post 'alertn/bloqueo_de_cuenta'



  #, to: 'alertn#observaciones'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :home, only: [:index, :create]
  resources :trcestatus


   # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/views/change_perfil/mandar_permisos_signup.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="viewport" content="width=device-width"/>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Alerts e.g. approaching your limit</title>
  <style type="text/css">
    * {
      margin: 0;
      padding: 0;
      font-family: "Avenir Medium", "avenir", "Avenir", Avenir, "Avenir Black", "Avenir Heavy", "Avenir Roman";
      box-sizing: border-box;
      font-size: 14px
    }

    img {
      max-width: 100%
    }

    body {
      -webkit-font-smoothing: antialiased;
      -webkit-text-size-adjust: none;
      width: 100% !important;
      height: 100%;
      line-height: 1.6
    }

    table td {
      vertical-align: top
    }

    body {
      background-color: #f6f6f6
    }

    .body-wrap {
      background-color: #f6f6f6;
      width: 100%
    }

    .container {
      display: block !important;
      max-width: 600px !important;
      margin: 0 auto !important;
      clear: both !important
    }

    .content {
      max-width: 600px;
      margin: 0 auto;
      display: block;
      padding: 20px
    }

    .main {
      background: #fff;
      border: 1px solid #e9e9e9;
      border-radius: 3px
    }

    .content-wrap {
      padding: 20px
    }

    .content-block {
      padding: 0 0 20px
    }

    .header {
      width: 100%;
      margin-bottom: 20px
    }

    .footer {
      width: 100%;
      clear: both;
      color: #999;
      padding: 20px
    }

    .footer a {
      color: #999
    }

    .footer a, .footer p, .footer td, .footer unsubscribe {
      font-size: 12px
    }

    h1, h2, h3 {
      font-family: "Avenir Medium", "avenir", "Avenir", Avenir, "Avenir Black", "Avenir Heavy", "Avenir Roman";
      color: #000;
      margin: 40px 0 0;
      line-height: 1.2;
      font-weight: 400
    }

    h1 {
      font-size: 32px;
      font-weight: 500
    }

    h2 {
      font-size: 24px
    }

    h3 {
      font-size: 18px
    }

    h4 {
      font-size: 14px;
      font-weight: 600
    }

    ol, p, ul {
      margin-bottom: 10px;
      font-weight: 400
    }

    ol li, p li, ul li {
      margin-left: 5px;
      list-style-position: inside
    }

    a {
      color: #003057;
      text-decoration: underline
    }

    .btn-primary {
      text-decoration: none;
      color: #FFF;
      background-color: #003057;
      border: solid #003057;
      border-width: 5px 10px;
      line-height: 2;
      font-weight: 700;
      text-align: center;
      cursor: pointer;
      display: inline-block;
      border-radius: 5px;
      text-transform: capitalize
    }

    .last {
      margin-bottom: 0
    }

    .first {
      margin-top: 0
    }

    .aligncenter {
      text-align: center
    }

    .alignright {
      text-align: right
    }

    .alignleft {
      text-align: left
    }

    .clear {
      clear: both
    }

    .alert {
      font-size: 16px;
      color: #fff;
      font-weight: 500;
      padding: 20px;
      text-align: center;
      border-radius: 3px 3px 0 0
    }

    .alert a {
      color: #fff;
      text-decoration: none;
      font-weight: 500;
      font-size: 16px
    }

    .alert.alert-warning {
      background: #f8ac59
    }

    .alert.alert-bad {
      background: #ed5565
    }

    .alert.alert-good {
      background: #003057;
      font-size: 16px;
    }

    .invoice {
      margin: 40px auto;
      text-align: left;
      width: 80%
    }

    .invoice td {
      padding: 5px 0
    }

    .invoice .invoice-items {
      width: 100%
    }

    .invoice .invoice-items td {
      border-top: #eee 1px solid
    }

    .invoice .invoice-items .total td {
      border-top: 2px solid #333;
      border-bottom: 2px solid #333;
      font-weight: 700
    }

    @media only screen and (max-width: 640px) {
      h1, h2, h3, h4 {
        font-weight: 600 !important;
        margin: 20px 0 5px !important
      }

      h1 {
        font-size: 22px !important
      }

      h2 {
        font-size: 18px !important
      }

      h3 {
        font-size: 16px !important
      }

      .container {
        width: 100% !important
      }

      .content, .content-wrap {
        padding: 10px !important
      }

      .invoice {
        width: 100% !important
      }
    }
  </style>
</head>

<body>

<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" width="600">
      <div class="content">
        <table class="main" width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td class="alert alert-good">
              <%= t('views.mandar_permisos.info') %>
            </td>
          </tr>
          <tr>
            <td class="content-wrap">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <%= t('views.mandar_permisos.new') %>
                  </td>
                </tr>

                <tr>
                  <td class="content-block">
                    <%= t('views.mandar_permisos.username') %>: <strong><%= @name_user %> <%= @last_user %></strong>
                  </td>
                </tr>
                <tr>
                  <td class="content-block">
                    <%= t('views.mandar_permisos.email') %>: <strong><%= @user_email %></strong>
                  </td>
                </tr>
                <tr>
                  <td class="content-block">
                    <!--</h1><%#= link_to "Permits", user_url(:index), class: 'btn-primary' %>-->
                    </h1><%= link_to t('views.mandar_permisos.permits'), user_url(@id_usr), class: 'btn-primary' %>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </div>
    </td>
    <td></td>
  </tr>
</table>

</body>
</html>